export const quotes = [
    ["You must be the change you wish to see in the world.", "- Mahatma Gandhi"], 
    ["Spread love everywhere you go. Let no one ever come to you without leaving happier.", "- Mother Teresa"],
    ["The only thing we have to fear is fear itself.", "- Franklin D. Roosevelt"],
    ["Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate: only love can do that.", "- Martin Luther King Jr."],
    ["Be yourself; everyone else is already taken.", "- Oscar Wilde"],
    ["If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", "- Oprah Winfrey"],
    ["The future belongs to those who believe in the beauty of their dreams", "- Eleanor Roosevelt"],
    ["The greatest glory in living lies not in never falling, but in rising every time we fall.", "- Nelson Mandela"],
    ["The way to get started is to quit talking and begin doing.", "- Walt Disney"],
    ["I find that the harder I work, the more luck I seem to have.", "- Thomas Jefferson"],
    ["You will face many defeats in life, but never let yourself be defeated.", "- Maya Angelou"],
    ["The secret of success is to do the common thing uncommonly well.", "- John D. Rockefeller Jr."],
    ["Success is not final; failure is not fatal: It is the courage to continue that counts.", "- Winston S. Churchill"],
    ["Everything you can imagine is real.", "- Pablo Picasso"],
    ["If you want to make your dreams come true, the first thing you have to do is wake up.", "- J.M. Power"],
    ["It is better to fail in originality than to succeed in imitation.", "- Herman Melville"],
    ["Before anything else, preparation is the key to success.", "- Alexander Graham Bell"],
    ["Winning isn't everything, but wanting to win is.", "- Vince Lombardi"],
    ["Whether you think you can or you think you can't, you're right.", "- Henry Ford"],
    ["You miss 100% of the shots you don't take.", "- Wayne Gretzky"],
    ["I alone cannot change the world, but I can cast a stone across the water to create many ripples.", "- Mother Teresa"],
    ["You become what you believe.", "- Oprah Winfrey"],
    ["The most difficult thing is the decision to act; the rest is merely tenacity.", "- Amelia Earhart"],
    ["How wonderful it is that nobody need wait a single moment before starting to improve the world.", "- Anne Frank"],
    ["An unexamined life is not worth living.", "- Socrates"],
    ["Everything you've ever wanted is on the other side of fear.", "- George Addair"],
    ["Dream big and dare to fail.", "- Norman Vaughan"],
    ["It does not matter how slowly you go as long as you do not stop.", "- Confucius"],
    ["I have learned over the years that when one's mind is made up, this diminishes fear.", "- Rosa Parks"],
    ["I didn't fail the test. I just found 100 ways to do it wrong.", "- Benjamin Franklin"],
    ["With great power comes great responsibility.", "- Stan Lee"],
    ["Dreaming, after all, is a form of planning.", "- Gloria Steinem"]
];